### ISSUE TITLE
Hard/impossible to show help

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx-watch#14]
I think `dnx-watch` without arguments should show help. At the moment it just starts watching the project in the folder (if the `project.json` happens to be there) but since there is no command for the application it just shows the generic dnx help

`dnx-watch --help` does not show help. The way I eventually was able to get help was by invoking `dnx-watch --help --dnx-args --verify`

**Comment by muratg** [comment]
@victorhurdugaci thoughts?

**Comment by victorhurdugaci** [comment]
Will fix this as part of the rewrite. It's not a critical bug but the user experience sucks.

**Comment by muratg** [comment]
@victorhurdugaci Could you add the proper labels to this (and the other dnx-watch items) so that they can be tracked in the release notes?  Thanks.
