### ISSUE TITLE
dnx-watch should exit if there is nothing to watch

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx-watch#15]
if `dnx-watch` is started in the folder where there is no `project.json` file it will wait for the `project.json` to be created. I think it is more likely that `dnx-watch` was started in a wrong directory instead that it was started because I am planning to create a project in the folder the `dnx-watch` was started in. I think it would be just better to exit and write an error message (and possibly show help) instead of waiting for a new project to be created.

**Comment by muratg** [comment]
:+1:

**Comment by davidfowl** [comment]
I don't know if it agree with that. I can start without a project and add it and things wil just work. I can see the error case but I don't think it needs to quit immediately

**Comment by moozzyk** [comment]
Yes you can. The question is how often you start watching before you create a new project vs. how often you start watching in a wrong folder.

**Comment by muratg** [comment]
Perhaps it should just print out a warning saying "There's no project.json in the current folder. Start your project by creating one" or something. This way, you'd know if you started it in the wrong place, or you can go ahead and start creating your project then.

**Comment by davidfowl** [comment]
yes

**Comment by victorhurdugaci** [comment]
Related to this there's another case: you delete the project.json file. I think the watcher should have the same behavior when there's no project.json or when you delete. It should just stay there and watch

**Comment by moozzyk** [comment]
@victorhurdugaci - deleting and recreating project.json file actually works. I thought it did not work but I tried it on CoreClr MacOs where dnx-watch does not seem to work at all.

**Comment by victorhurdugaci** [comment]
This is no longer applicable because the watcher always runs in the context of a project.
