### ISSUE TITLE
Remove unneeded code

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx-watch#16]
Looks like we [assign](https://github.com/aspnet/dnx-watch/blob/dev/src/Microsoft.Dnx.Watcher/Program.cs#L75-L79) the `ShowHelp` action to `app.OnExecute` but then a few lines below we [overwrite](https://github.com/aspnet/dnx-watch/blob/dev/src/Microsoft.Dnx.Watcher/Program.cs#L98) it with the application logic. The first assignment is always overwritten so it's not needed. 
As a sidenote - [returning 2](https://github.com/aspnet/dnx-watch/blob/dev/src/Microsoft.Dnx.Watcher/Program.cs#L78) does not seem to be correct - I believe we should return `0` for `--help`.

Related to #14

**Comment by BrennanConroy** [comment]
cbc201ac26114f211dba53788b155717dee5983d
