### ISSUE TITLE
The way dnx-watch handles parameters is confusing

### ISSUE THREAD

**Issue by moozzyk** [aspnet/dnx-watch#18]
With `dnx-watch` there are really three separate parts that need parameters - `dnx-watch`, `dnx` and the app itself. The rules about what parameters are used where (especially between `dnx-watch` and `dnx`) is confusing. This mostly especially shows when running `dnx-watch` for a project that is not in the current directory. e.g. I can run my app like this:

`dnx --project .\src\HelloDNX\project.json run`

However when I run: 

`dnx-watch --project .\src\HelloDNX\project.json run`

I get: 
```
PS C:\Users\xxxx\documents\visual studio 2015\Projects\HelloDNX> dnx-watch --project .\src\HelloDNX\project.json run
[DnxWatcher] fail: Error(s) reading project file 'C:\Users\xxxxx\documents\visual studio 2015\Projects\HelloDNX\project.json':
[DnxWatcher] fail:
[DnxWatcher] info: Fix the error to continue.
```
so `dnx-watch` is trying to use my current folder even though the path to the project was passed with the `--project` parameter.

On the other hand I can run this command:

`dnx-watch --project .\src\HelloDNX\project.json --dnx-args run`

and it will work. Even though `--dnx-args` separates `dnx-watch` arguments from `dnx` arguments the `--project` is actually being passed to `dnx`. 

Another issue is that if the user passes `-p` after `--dnx-args` stuff breaks  because dnx now receives to -p parameters:
```
PS C:\Users\xxxxx\documents\visual studio 2015\Projects\HelloDNX> dnx-watch --project .\src\HelloDNX\project.json --dnx-args -p .\src\HelloDnx\project.json ru
n
[DnxWatcher] info: Running dnx with the following arguments: --project .\src\HelloDNX\project.json -p .\src\HelloDnx\project.json run
[DnxWatcher] info: dnx process id: 68280
Error: Unable to load application or execute command '-p'. Available commands: HelloDNX.
```

**Comment by muratg** [comment]
We need to look at this experience as we start using dotnet CLI instead of dnx. If this is still an issue with the dotnet CLI, we should consider fixing it otherwise close.
