### ISSUE TITLE
Unable to install? 

### ISSUE THREAD

**Issue by shanselman** [aspnet/dnx-watch#25]
What's the debugging process when something this simple doesn't work? I see another issue that had the same thing but then theirs just started working later.

    C:\Users\Scott\Desktop>dnvm use default
    Adding C:\Users\Scott\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8\bin to process PATH

    C:\Users\Scott\Desktop>dnu commands install Microsoft.Dnx.Watcher
    Microsoft .NET Development Utility Clr-x86-1.0.0-beta8-15858

    Unable to locate the package Microsoft.Dnx.Watcher
    Failed to install Microsoft.Dnx.Watcher

**Comment by victorhurdugaci** [comment]
Turns out that the `nuget.org` package source was disabled.

**Comment by poke** [comment]
I’m having the same issue and no idea what to do. Where would the NuGet package source be configured? There’s no NuGet.Config in `~/.dnx`.

**Comment by BrennanConroy** [comment]
~/.config/NuGet I think

**Comment by doggy8088** [comment]
`%appdata%\NuGet\NuGet.Config` I think.

**Comment by DarranShepherd** [comment]
Just experienced this myself. For anyone else stumbling across this, it turns out `dnu feeds list` shows configured feeds, whether they're disabled (mine were) and the NuGet config files in use to go and re-enable them.

Why my AppData nugget.config had disabled nuget.org, I do not know, however.

**Comment by victorhurdugaci** [comment]
That's a known issue and the VS team is looking into it. Sometimes the nuget.org source gets disabled.
