### ISSUE TITLE
Ability use as command in project.json

### ISSUE THREAD

**Issue by RaveNoX** [aspnet/dnx-watch#26]
Hello!
It will be great to add ability to declare watcher as command for Asp.Net project, something like that:

```json
  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",    
    "watch": "Microsoft.Dnx.Watcher web"
  }
~~~

**Comment by victorhurdugaci** [comment]
Interesting suggestion but it would not work very well with the watcher story because we want the watcher to be able to detect and watch invalid project.json files. If the project.json file that contains the watch command is invalid, the watcher wouldn't even start.

**Comment by victorhurdugaci** [comment]
Commands go away in dotnet so this cannot happen anymore in the new world. Sorry
