### ISSUE TITLE
How I can find out user installed dnx-watcher?

### ISSUE THREAD

**Issue by Codenator81** [aspnet/dnx-watch#27]
@dmccaffery 
Referenced issue tugberkugurlu/gulp-dnx#26

**Comment by muratg** [comment]
We currently do not have this feature implemented. Tracking bug: https://github.com/aspnet/dnx/issues/2870

You can do a check this manually by testing the existence of the .cmd (or .sh) file in `%userprofile%\.dnx\bin\` (or `~/.dnx/bin on OS X/Linux`).  However, this could be brittle, as in if we end up changing the folder structure or location, this check would be incorrect.

**Comment by luisrudge** [comment]
@muratg is there a way to list all commands installed?

**Comment by luisrudge** [comment]
Yeah.. Listing dnu commands is the way to go. any eta for that?

**Comment by victorhurdugaci** [comment]
As a temporary workaround you could use `where dnx-watch` (win) or `whereis dnx-watch` (*nix).

**Comment by dmccaffery** [comment]
How did I get referenced by this? Was I drinking too much or something? lolol

**Comment by Codenator81** [comment]
@dmccaffery  That was me )))

**Comment by victorhurdugaci** [comment]
Closing this because I assume it is solved. Summary of the resolution: before we have `dnu commands list`, the way to check for `dnx-watch` is where/whereis/type
