### ISSUE TITLE
Is dnx-watch ok to use on Linux?

### ISSUE THREAD

**Issue by borgdylan** [aspnet/dnx-watch#30]
I tried to use dnx-watch but it blew up saying the directory was not found? Do I have to specify the directory to be watched and if yes how? dnx-watch does not have a help output that I can consult.

**Comment by victorhurdugaci** [comment]
`dnx-watch --project C:\myproject --dnx-args web` for example to watch the project in C:\myproject and pass argument `web` to dnx

**Comment by borgdylan** [comment]
Thanks for clarifying. The examples on the web show a different set of arguments which did not work.

**Comment by victorhurdugaci** [comment]
Can you point me to those examples, please?



On Tue, Nov 3, 2015 at 11:05 PM -0800, "Dylan Borg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for clarifying. The examples on the web show a different set of arguments which did not work.

-

**Comment by borgdylan** [comment]
These are just three of them:

http://ardalis.com/get-started-with-dnx-watch
http://www.codeproject.com/Articles/1045614/dnx-watch-A-no-compile-developer-experience
http://nojaf.com/2015/10/25/test-driven-development-with-dnx-watch-and-xunit/

**Comment by Peluko** [comment]
Did you get it working on Linux?

I've been trying on Ubuntu with no luck. First, after install (`dnu commands install Microsoft.Dnx.Watcher`) it doesn't get into PATH. Second, I've found a `dnx-watch` bash script on `~/.dnx/packages/Microsoft.Dnx.Watcher/1.0.0-beta8/app/`, but when I run it on my project I get the message `Error: Unable to load application or execute command 'dnx-watch'. Available commands: web, ef`.
The bash script contains one line: `dnx --appbase "$(dirname $0)" Microfot.Dnx.ApplicationHost dnx-watch $@`

**Comment by Peluko** [comment]
Ok, following instructions from http://ardalis.com/get-started-with-dnx-watch I've reinstalled dnx-watch, but this time requesting a specific version: `dnu commands install Microsoft.Dnx.Watcher 1.0.0-beta8`

Now it works as expected.

**Comment by muratg** [comment]
Looks like it's working fine though it would be nice to get the community blogs etc updated with the correct params.  Closing this one.
