### ISSUE TITLE
dnx-watch doesn't wait for web, but does wait for help

### ISSUE THREAD

**Issue by rhires** [aspnet/dnx-watch#36]
I thought this was a bit comical when I came across it. This does not cause dnx-watch to show that it will watch:

    dnx-watch web
    [DnxWatcher] info: Running dnx with the following arguments: --project /Users/vscode/Projects/TestProject/project.json web
    [DnxWatcher] info: dnx process id: 46588
    info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
    info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT CASE
          WHEN EXISTS (
              SELECT 1 ... 
    Hosting environment: Production  
    Now listening on: http://localhost:5000
    Application started. Press Ctrl+C to shut down.

whereas this says it's waiting to watch:

     dnx-watch help
    [DnxWatcher] info: Running dnx with the following arguments: --project /Users/vscode/Projects/TestProject/project.json help
    [DnxWatcher] info: dnx process id: 46804
    Error: Unable to load application or execute command 'help'. Available commands: web, ef.  
    [DnxWatcher] fail: dnx exit code: 1
    [DnxWatcher] info: Waiting for a file to change before restarting dnx...

And then it hangs. I have to kill it via the command line. Running on Mono on Mac. 
So I don't know if the SQL statement getting executed then shown by the logger is causing it to just not show that it's watching or not. In spite of that, it doesn't notice when my files change and get saved, as in the first case above. 

Also, I hate putting "it doesn't work" without enough info...so if there is more detail I can provide, I would be happy to.

**Comment by muratg** [comment]
@rhires Yeah I think we should improve the status output for the first case.

The second case seems like a bug. If there's an unknown bug it still seems to attempt to watch.

**Comment by muratg** [comment]
@victorhurdugaci can you have a look?

**Comment by victorhurdugaci** [comment]
@rhires, thanks for reporting this! This bug will be solved by the fix to https://github.com/aspnet/dnx-watch/issues/14 so closing this as duplicate
