### ISSUE TITLE
Error installing dnx-watch

### ISSUE THREAD

**Issue by markentingh** [aspnet/dnx-watch#38]
Using rc1-final, coreclr x64, i get the error FindPackageById: Microsoft.Extensions.Logging an error occurred while sending the request.

Is dnx-watch not supported by rc1-final yet? I tried installing beta8, but it installs rc1 instead, with an alias of beta8.

**Comment by markentingh** [comment]
Also, you should know that im using https://nuget.org/api/v2/

**Comment by muratg** [comment]
What OS are you using?  Also, what was the command line you used to install dnx-watch?

**Comment by markentingh** [comment]
Windows 7 64-bit, &  "dnu commands install Microsoft.Dnx.Watcher"

**Comment by markentingh** [comment]
Also, it works just fine on my Windows 10 machine. On Windows 7, I made sure dnvm list was using the correct clr (dnvm use 1.0.0-rc1-final -r coreclr -arch x64). Then I executed "dnu commands install Microsoft.Dnx.Watcher".

**Comment by muratg** [comment]
Does it still fail for you?

@victorhurdugaci

**Comment by victorhurdugaci** [comment]
what feeds do you have in the global  nuget.config file?

**Comment by markentingh** [comment]
I should probably reinstall Visual Studio on Windows 7, since I have been using ASP.net 5 CoreCLR ever since beta3, and RC1 is out now. I'm sure there are many breaking changes that are preventing me from moving on.

**Comment by victorhurdugaci** [comment]
You don't need VS to install/run the watcher...

**Comment by markentingh** [comment]
True... Windows 7 dnvm just acts differently from Windows 10, I've noticed. Some dependencies work fine on Windows 10, but then I have to upgrade all my dependencies when testing the same project on Windows 7, or else it won't work. Also, I've noticed that I can run CoreCLR x64 on Windows 10 just fine, but in order to do a "dnu restore" on Windows 7, I have to use x86, even though I'm using Windows 7 64-bit.

**Comment by muratg** [comment]
@markentingh Could you share your nuget.config on your Windows 7 machine?  Possibly you don't have nuget.config on the machine.

**Comment by victorhurdugaci** [comment]
@markentingh also tell us what version of dnvm you're using

**Comment by victorhurdugaci** [comment]
I am going to assume this was a feed error. If you are still seeing the issue, please reopen.
