### ISSUE TITLE
dnx-watch exit on Mono segfault

### ISSUE THREAD

**Issue by hantleman** [aspnet/dnx-watch#45]
After some days working in docker on linux mvc application throw segfault exception and wait.
Stacktrace:

Native stacktrace:

        mono() [0x4b23dc]
        mono() [0x508a0e]
        mono() [0x428fad]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0xf0a0) [0x7f8a141bc0a0]
        /lib/x86_64-linux-gnu/libc.so.6(cfree+0x19) [0x7f8a13e9c939]
        mono() [0x4e80dd]
        mono() [0x421f22]
        mono(mono_conc_hashtable_remove+0x125) [0x624695]
        mono() [0x4220b4]
        mono() [0x5a6f02]
        mono() [0x5b0610]
        mono() [0x5a1c89]
        mono() [0x5a1cc0]
        mono() [0x5a215d]
        mono() [0x5874e8]
        mono() [0x623a36]
        /lib/x86_64-linux-gnu/libpthread.so.0(+0x6b50) [0x7f8a141b3b50]
        /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f8a13efd95d]

Debug info from gdb:

> =================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
> =================================================================

[DnxWatcher] fail: dnx exit code: 134
[DnxWatcher] info: Waiting for a file to change before restarting dnx...

This is not a good way on production. Is there any ways to restart application on segfaults?

**Comment by muratg** [comment]
@victorhurdugaci could you investigate?

**Comment by victorhurdugaci** [comment]
Dotnet watch is now CoreCLR only. This is no longer applicable
