### ISSUE TITLE
Add support for exit on change scenario

### ISSUE THREAD

**Issue by pakrym** [aspnet/dnx-watch#47]
By adding command line switch.
Used for running dotnet-watch under HttpPlatformHandler
Related to https://github.com/aspnet/IISIntegration/issues/34

**Comment by muratg** [comment]
@pakrym If you're able to take this one in, please do.

**Comment by victorhurdugaci** [comment]
This should happen after the dotnet conversion

**Comment by tuespetre** [comment]
Is this going to aid in debugging, or are there other improvements being made in that arena, as far as being able to continuously run the debugger on an application running with `watch`?

**Comment by victorhurdugaci** [comment]
I assume that you refer to the fact that if you have a debugger attached to the app being watched it will not get reattached. This work item is not going to aid debugging and there's no plan to do any work in that area.

But, you can always pass the "--debug" flag to dnx and the watcher will start dnx waiting for a debugger.
