### ISSUE TITLE
Changing dependencies breaks the watcher flow

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx-watch#8]
Not really a watcher bug but a DNX one:

![image](https://cloud.githubusercontent.com/assets/95136/10129542/2696a15e-6574-11e5-9924-d8f1919831dc.png)

We made a decision to not throw the process if dependencies are out of date. This currently breaks the flow because the files have to change again to trigger a restart.

**Comment by muratg** [comment]
> Not really a watcher bug but a DNX one:

So file it in DNX.

**Comment by muratg** [comment]
Putting into 1.0.0 backlog in case you prefer to work around it in the watcher (instead of changing DNX behavior)

**Comment by victorhurdugaci** [comment]
`dnx-watch` shouldn't run restore because it has no idea if the change to the `project.json` file require restore or not (e.g changing the author doesn't require restore but a new dependency does).

If you change `project.json` then you have to run `restore` yourself.
